horde/horde

- framework/Core/lib/Horde/Core/Factory/HashTable.php
- horde/config/conf.xml
with this change it is possible to change the used database so that no longer all keys go to the default database
see https://github.com/nrk/predis/wiki/Quick-tour#parameters
> add option to specify the redis database index to connect to

- ansel/package.xml
According to 2.0alpha1 changelog which says: "Remove support for no longer available openCV extension."
> Ansel: Remove unneeded dependency on opencv

- framework/Compress/lib/Horde/Compress/Tnef/Icalendar.php
Wrong case in class-name causes Composer autoloader to not find the class, when Horde_Compress_Tnef eg. in line 621 does a new Horde_Compress_Tnef_Icalendar();
Should be easy to reproduce in Horde when you view a meeting request encapsulated as TNEF/winmail.dat.
Ralf
> Fix for PHP Fatal error: Class 'Horde_Compress_Tnef_Icalendar' not found

- imp/lib/Ajax/Imple/ItipRequest.php
Hello,
i noticed one php error when i tried to delete one event using itip action on imp,
the event has been deleted previously, so i have one exception in block code starting at line 94.
$range is not set when kronolith API is called on line 106
moving up avoids the error and has no other side effect, i think.
thanks in advance.
> On exception $range is not set, moving up to avoid php error

- framework/lz4/horde_lz4.c
- framework/lz4/horde_lz4.h
$ php -v
PHP 7.0.0-dev (cli) (built: Mar 25 2015 14:40:01) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies
with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
$ php  /usr/bin/phpunit .
PHPUnit 4.5.1 by Sebastian Bergmann and contributors.
............
Time: 19 ms, Memory: 4.00Mb
OK (12 tests, 14 assertions)
> Fix PHP 7 compatibility

- kronolith/lib/Event.php
Catched this error,
PHP Fatal error:  Call to a member function get() on a non-object in (...)/kronolith/lib/Event.php on line 3149
missing session variable,
setting as global, on beginning of the function, fixes the error.
The commit that introduced this error is this:
thttps://github.com/horde/horde/commit/10237a37fb797785e4a44d416e0e4552bea26dad
Thanks in advance
> Added missing global variable

- passwd/lib/Driver/Kolab.php
Patch by Mike Gabriel, originally reported at https://bugs.debian.org/780670
> Fix typo in Kolab passwd driver

- framework/Mail/lib/Horde/Mail/Transport/Mail.php
We use the great Horde_Mail lib for https://github.com/owncloud/mail and getting this error:
```
556 {"reqId":"SXF2i8qT\/tzWR9JfX3t5","remoteAddr":"127.0.0.1","app":"PHP","message":"mail() expects parameter 1 to be string, array given at \/home\/gomez\/public_html\/mail_dev\/core\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Mail\/Horde\/Mail\/Transport\/Mail.php#103","level":3,"time":"2015-06-24T12:20:3    5+00:00"}
```
This PR fixes the bug, is it good to get merged?
> Fix string expected

- framework/Imap_Client/lib/Horde/Imap/Client/Exception.php
Translation exception hides Horde_Imap_Client_Exception.
I am trying to list all mailboxes. If I catch this exception then command continues and I get list of mailboxes. 
I believe error translations should not be a requirement.
Debug log when connecting to gmail and translation exception is NOT caught:
```
C: 3 ENABLE CONDSTORE UTF8=ACCEPT
C: 4 LIST () "" (*)
S: * ENABLED CONDSTORE UTF8=ACCEPT
S: 3 OK Success
>> Command 3 took 0.1214 seconds.
S: 4 BAD Could not parse command
>> Command 4 took 0.1214 seconds.
C: 5 LOGOUT
S: * BYE LOGOUT Requested
S: 5 OK 73 good day (Success)
>> Command 5 took 0.1196 seconds.
```
and when translation exception is caught:
```
C: 3 ENABLE CONDSTORE UTF8=ACCEPT
C: 4 LIST () "" (*)
S: * ENABLED CONDSTORE UTF8=ACCEPT
S: 3 OK Success
>> Command 3 took 0.121 …
```
> catch translation exception when there is server response exception

- framework/Util/test/Horde/Util/TransliterateTest.php
This is related to iconv, where "Þ" is now translated as "TH"
(like with intl).
Fedora rawhide, glibc 2.21.90:
$ php -r 'var_dump(iconv("UTF-8", "ASCII//TRANSLIT", "Þ"));'
string(2) "TH"
Fedora 21, glibc 2.20:
$ php -r 'var_dump(iconv("UTF-8", "ASCII//TRANSLIT", "Þ"));'
string(1) "?"
Detected by Fedora CI (aka Koschei) See https://apps.fedoraproject.org/koschei/package/php-horde-Horde-Util
> Fix failed test with newer glibc

- framework/Kolab_Storage/lib/Horde/Kolab/Storage/Driver/Imap.php
When using the new sync token strategy, we have to get
the folder status before calling sync(). That's the same
way the non-token based sync works.
Internally, Horde_Imap_Client uses "uidnext" to determine
if there are any new messages. If we first sync and then
get the folder status (and we force a status refresh in our
status() function), we might write down a higher
"uidnext" value than the one used for the sync() call.
This fixes vanishing contacts on changes from foreign Kolab clients
when using turba and ActiveSync at the same time: We didn't register
the new message (=updated contact), only the delete of the old IMAP message.
> Kolab_Storage: Fix sync race condition when using sync token

- framework/Core/js/calendar.js
The old method always assumes that the 01.01. is in the first calendar week, but according to the ISO standard (https://en.wikipedia.org/wiki/ISO_week_date) the 04.01. is always in week number 1
> Fixed week numbering in JS calendar

- framework/Nls/package.xml
- framework/Socket_Client/package.xml
I have carefully tested these 2 frameworks and they both play well with php7.
We need this to bump our projects supported version.
https://github.com/owncloud/mail/pull/1262
> bump Socket_Client and Nls supported PHP version to 7

- framework/Core/js/calendar.js
The calculation of the last week of year was still wrong, this works with getWeek from js/date/date.js
and we don't need to functions which do the same thing.
> Use getWeek from js/date/date.js

- ingo/test/Ingo/Unit/ScriptTest.php
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ScriptTester has a deprecated constructor
> ScriptTester has a deprecated constructor

- framework/Form/lib/Horde/Form.php
This caused a bug when using multiple sections and the variable shouldn't be removed from the current section.
> Bugfix: removeVariable from $section not current

- framework/Form/lib/Horde/Form/Type.php
incomplete date arrays may be corrected by Horde_Date causing not wanted results
e.g. 2016-NULL-NULL will become 2015-11-30
> if (month < 1) { year--; month = month%12 }
> [and similar with the day]
this can either happen if for e.g.
1. reloading form on change and only the year has been set (until now)
2. the year should be pre-selected by setting it over ->setDefault(array('year'=>date('Y')))
> fixed handling of incomplete date arrays

- kronolith/lib/Kronolith.php
as the method(s) below rely on that they have a Kronolith_Attendee Object
> Fixed format of mail_attendees for ext organizer

- kronolith/lib/Icalendar/Handler/Dav.php
There are still things I'm not sure about:
- if I should add a check if the event (or in the case of ext. organizer, if the attendance response) has been changed before sending the ITip notification
- what is with the davDeleteObject method from lib/Application.php? (maybe the ITIP_CANCEL should be changed to ITIP_REPLY too, and the attendance response to decline?)
> Send ITIP_REPLY message when saving ext. event

- framework/Cache/test/Horde/Cache/MongoTest.php
- framework/Mongo/bundle/composer.json
- framework/Mongo/lib/Horde/Mongo/Client.php
- framework/Test/lib/Horde/Test/Factory/Mongo.php
use alcaeus/mongo-php-adapter  compatibility layer and mongodb extension
With PHP 5.6 and mongo extension
```
$ phpunit MongoTest.php  --verbose
PHPUnit 5.4.5 by Sebastian Bergmann and contributors.
Runtime:       PHP 5.6.22
Configuration: /work/GIT/horde/framework/Cache/test/Horde/Cache/phpunit.xml
........                                                            8 / 8 (100%)
Time: 481 ms, Memory: 13.50MB
OK (8 tests, 21 assertions)
```
With PHP 7.0 and mongodb extension
```
$ phpunit MongoTest.php  --verbose
PHPUnit 5.4.5 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.0.8RC1
Configuration: /work/GIT/horde/framework/Cache/test/Horde/Cache/phpunit.xml
........                                                            8 / 8 (100%)
Time: 475 ms, Memory: 4.00MB
OK (8 tests, …
```
> for PHP 7, use alcaeus/mongo-php-adapter 

- framework/Date_Parser/lib/Horde/Date/Parser/Locale/Pt.php
- framework/Db/lib/Horde/Db/SearchParser.php
- framework/Kolab_Format/lib/Horde/Kolab/Format/Xml/Annotation.php
Despite these components are already tagged as PHP 7 compatible, I found some remaining usage of the ereg extension which is deprecated for years and now removed.
Tips: phpcompatinfo is very usefull for such check ;)
> Issue ereg / PHP 7

- framework/ManageSieve/lib/Horde/ManageSieve.php
One of our users run into an other namespace problem, which I fixed here.
Ralf
> fix PHP Fatal error: Class 'Horde\Auth_SASL' not found

- framework/Rdo/lib/Horde/Rdo/Mapper.php
if there was a relationship added using a left join
the fields of the joined table may be empty
> check if relationship is empty (LEFT JOIN)

- framework/Rdo/lib/Horde/Rdo/Base.php
this method should be used when handing over to Horde_Variables::merge
or otherwise all lazy fields and relationships are merged too.
this can cause quite some trouble if you have many relationships and what to hand your table over to a Form because you'd like to edit your entry
> make entities convertible to an array

- framework/Icalendar/lib/Horde/Icalendar.php
From http://php.net/manual/en/functions.anonymous.php
`As of PHP 5.4.0, when declared in the context of a class, the current class is automatically bound to it, making $this available inside of the function's scope. `
So with PHP 5.3
```
+ php /usr/bin/phpunit --verbose .
PHPUnit 3.7.34 by Sebastian Bergmann.
Configuration read from /builddir/build/BUILD/php-horde-Horde-Icalendar-2.1.5/Horde_Icalendar-2.1.5/test/Horde/Icalendar/phpunit.xml
.....F...........PHP Fatal error:  Using $this when not in object context in /builddir/build/BUILD/php-horde-Horde-Icalendar-2.1.5/Horde_Icalendar-2.1.5/lib/Horde/Icalendar.php on 
```
Having to put this method public and static is a but ugly, but... I don't see other simple way
> fix PHP 5.3 compatibility

- framework/Crypt/lib/Horde/Crypt/Pgp/Backend/Binary.php
From gnupg NEWS file
```
Noteworthy changes in version 2.1.12 (2016-05-04)
-------------------------------------------------
...
* gpgsm: Add option --pinentry-mode to support a loopback pinentry.
...
```
So, test suite fails on RHEL 6 (gnupg 2.0.14) and 7  (gnupg 2.0.22)
```
PHPUnit 5.7.19 by Sebastian Bergmann and contributors.
FEEEEFFEEEFFE.EEF...                                              20 / 20 (100%)
Time: 151 ms, Memory: 5.25MB
There were 10 errors:
1) Horde_Crypt_Pgp_BinaryTest::testPgpDecrypt with data set #0 (Horde_Crypt_Pgp Object (...))
Horde_Crypt_Exception: Could not decrypt PGP data.
/builddir/build/BUILD/php-horde-Horde-Crypt-2.7.7/Horde_Crypt-2.7.7/lib/Horde/Crypt/Pgp.php:659
/builddir/build/BUILD/php-horde-Horde-Crypt-2.7.7/Horde_Crypt-2.7.7/test/Horde/Crypt/Pgp/TestBa …
```
> '--pinentry-mode loopback' was introduce in gnupg 2.1.12

- framework/Imap_Client/lib/Horde/Imap/Client/Socket.php
Removed a sort of Horde_Imap_Client_Ids when cutting (partial) the result of a search. This sort it's unnecessary and broke the sorting done previously.
> Removed sort when cutting results

- framework/Imap_Client/lib/Horde/Imap/Client/Base.php
Exception: Error in IMAP command UID FETCH: QRESYNC not enabled (0.000 + 0.000 secs).
From https://tools.ietf.org/html/rfc5162 :
A client making use of this extension MUST issue "ENABLE QRESYNC" once it is authenticated.  A server MUST respond with a tagged BAD response if the QRESYNC parameter to the SELECT/EXAMINE command or the VANISHED UID FETCH modifier is specified and the client hasn't issued "ENABLE QRESYNC" in the current connection.
> Check is QRESYNC ENABLED

- imp/lib/Pgp.php
reset() *returns* the first element, so let's actually do what the
comment above says.
> fix pgp key lookup if more than one key is found

- ingo/config/conf.xml
- ingo/lib/Factory/Script.php
- ingo/lib/Form/Spam.php
- ingo/lib/Script/Maildrop.php
- ingo/lib/Script/Sieve.php
This PR adds support for boolean (yes/no) spam headers (such as those used by rspamd) to Ingo.
I have confirmed that the correct sieve rule is generated but am unable to test maildrop.
> ingo: Add support for boolean spam headers
